# Generated by Django 5.2.17 on 2026-08-09 09:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetricsDaily',
            fields=[
                ('metric_date', models.DateField(primary_key=True, serialize=False)),
                ('dau', models.PositiveIntegerField(default=0)),
                ('wau', models.PositiveIntegerField(default=0)),
                ('mau', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('post_views', models.PositiveIntegerField(default=0)),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('replies_created', models.PositiveIntegerField(default=0)),
                ('likes_created', models.PositiveIntegerField(default=0)),
                ('d1_retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('d7_retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('d30_retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='RetentionCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_date', models.DateField(db_index=True)),
                ('retention_day', models.PositiveSmallIntegerField()),
                ('cohort_size', models.PositiveIntegerField(default=0)),
                ('retained_users', models.PositiveIntegerField(default=0)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['-cohort_date', 'retention_day'],
                'constraints': [models.UniqueConstraint(fields=('cohort_date', 'retention_day'), name='unique_retention_cohort_day')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('react', 'React'), ('django', 'Django')], max_length=12)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.board')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='forum.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at', 'user'], name='analytics_a_occurre_455807_idx'), models.Index(fields=['event_name', 'occurred_at'], name='analytics_a_event_n_aeeca0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(db_index=True)),
                ('is_new_user', models.BooleanField(default=False)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('page_view_count', models.PositiveIntegerField(default=0)),
                ('board_view_count', models.PositiveIntegerField(default=0)),
                ('post_view_count', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('activity_date', 'user'), name='unique_user_activity_day')],
            },
        ),
    ]
