# Generated by Django 5.2.17 on 2026-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmetricsdaily',
            name='anonymous_page_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='anonymous_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='board_view_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='board_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='liking_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='page_view_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='post_view_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='posting_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='replying_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='unlikes_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivitydaily',
            name='unlike_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
