# Generated by Django 5.2.17 on 2026-08-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_productmetricsdaily_anonymous_page_views_and_more'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmetricsdaily',
            name='activated_new_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='anonymous_registrations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='anonymous_uv',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='creator_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='interaction_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmetricsdaily',
            name='read_only_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BehaviorRetentionCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_date', models.DateField(db_index=True)),
                ('first_day_segment', models.CharField(choices=[('inactive', '首日未激活'), ('read_only', '首日只读'), ('interaction', '首日互动'), ('creator', '首日创作者')], max_length=16)),
                ('retention_day', models.PositiveSmallIntegerField()),
                ('cohort_size', models.PositiveIntegerField(default=0)),
                ('retained_users', models.PositiveIntegerField(default=0)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['-cohort_date', 'first_day_segment', 'retention_day'],
                'constraints': [models.UniqueConstraint(fields=('cohort_date', 'first_day_segment', 'retention_day'), name='unique_behavior_retention_cohort')],
            },
        ),
        migrations.CreateModel(
            name='BoardMetricsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('post_views', models.PositiveIntegerField(default=0)),
                ('post_view_users', models.PositiveIntegerField(default=0)),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('posting_users', models.PositiveIntegerField(default=0)),
                ('replies_created', models.PositiveIntegerField(default=0)),
                ('replying_users', models.PositiveIntegerField(default=0)),
                ('likes_created', models.PositiveIntegerField(default=0)),
                ('liking_users', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.board')),
            ],
            options={
                'ordering': ['-metric_date', 'board_id'],
                'constraints': [models.UniqueConstraint(fields=('metric_date', 'board'), name='unique_board_metrics_day')],
            },
        ),
    ]
